name: Go

on:
  push:
    branches: [main]
    paths:
      - "**.go"
      - "sonar-project.properties"
  pull_request:
    branches: [main]
    paths:
      - "**.go"
      - "sonar-project.properties"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Run all tests and find code coverage
        run: go test -v -bench . -benchmem -coverprofile=coverage.out ./...

      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.8

      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
